added BasePanel Component
sidestream-tech/unified-auctions-ui pull request #158
Opened 2022-03-23 11:30 UTC by simontree

closes #152

2022-03-23 11:32 UTC, benediktkaiser requested changes

2022-03-23 11:32 UTC, benediktkaiser commented on frontend/.prettierrc
> +    "printWidth": 119,
Why did you do this?

2022-03-23 15:06 UTC, valiafetisov reviewed
- [ ] please add icons
- [ ] please add animation

2022-03-23 15:06 UTC, valiafetisov commented on frontend/components/common/BasePanel.vue
> +    <modal :visible="true" :mask-closable="false" :closable="false" :footer="null">
Why did you use a modal? The issue and the mock doesn't say anything about the modal 🙂

2022-03-23 15:06 UTC, valiafetisov commented on frontend/components/common/BasePanel.vue
> +                </div>
This should not be part of the `BasePanel`, but should be provided as content (in other words as a `<slot />`)

2022-03-23 15:06 UTC, valiafetisov commented on frontend/components/common/BasePanel.vue
> +        <div v-if="state === 'default'">
What is the `default` state? The issue doesn't mention it

2022-04-04 14:26 UTC, benediktkaiser commented
Closed by accident. Reopening this PR.

2022-04-04 16:11 UTC, closed without merging