Fixed Collateral Popup Table
sidestream-tech/unified-auctions-ui pull request #304
Opened 2022-06-15 10:22 UTC by fegbert

Closes #285 

**preview**

<img width=400 src=https://user-images.githubusercontent.com/47861849/173804929-0fb748a6-a136-4ecc-9941-b2e806462af9.gif />

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

2022-06-15 11:22 UTC, benediktkaiser submitted a review, later dismissed
Not really much to review hahaha

2022-06-17 15:26 UTC, LukSteib requested changes
- [x] Can't we just increase the width of the modal a little bit? Now it doesn't look that broken anymore due to horizontal scrollability but still first impression when opening the popup is not nice (see recording below)

https://www.loom.com/share/653f4e9b39794960a457c76705cd287f

2022-06-22 07:24 UTC, LukSteib approved these changes

2022-06-22 07:37 UTC, valiafetisov approved these changes

2022-06-22 07:38 UTC, merged