Fix currency overflow and incorrect icon
sidestream-tech/unified-auctions-ui pull request #377
Opened 2022-07-25 09:39 UTC by aomafarag

Closes #360 .

1.  
![image](https://user-images.githubusercontent.com/85403429/180747051-f4ab86b2-462e-4d56-93b7-fab7a2b49dc6.png)

2.
![image](https://user-images.githubusercontent.com/85403429/180746870-1df6ae08-96fd-4907-868e-9c0096ba86ab.png)

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

2022-07-25 11:11 UTC, zoey-kaiser requested changes
The changes for the issue look good. However I am not happy with the changes to the SurplusAuctionTransactionFlow stories. 

I would say, lets remove them from this PR and then you can view the comments on the other PR you created 😄

2022-07-25 12:08 UTC, zoey-kaiser approved these changes

2022-07-26 07:35 UTC, LukSteib approved these changes

2022-07-28 10:18 UTC, valiafetisov approved these changes

2022-07-28 10:25 UTC, merged