Quick fix for faulty overflow of auction tables
sidestream-tech/unified-auctions-ui pull request #384
Opened 2022-08-01 09:54 UTC by aomafarag

Closes #383.

![Screenshot from 2022-08-01 11-53-20](https://user-images.githubusercontent.com/85403429/182123179-99d5c36d-0a55-48e3-9497-72342db3cf8a.png)

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

2022-08-05 07:47 UTC, LukSteib approved these changes

2022-08-08 08:52 UTC, zoey-kaiser requested changes

2022-08-08 08:52 UTC, zoey-kaiser commented on frontend/components/auction/surplus/SurplusAuctionsTable.vue
> +import { SurplusAuction, SurplusAuctionTransaction } from 'auctions-core/src/types';
We used the wrong type in this file. Please remove the import of the `SurplusAuction` and fix the type (from SurplusAuction to SurplusAuctionTransaction) in this line:

https://github.com/sidestream-tech/unified-auctions-ui/blob/130fbb7e3b808954802cd635b160b9084dd9eced/frontend/components/auction/surplus/SurplusAuctionsTable.vue#L228

2022-08-09 14:43 UTC, valiafetisov approved these changes

2022-08-09 14:44 UTC, merged