Minor surplus fixes
sidestream-tech/unified-auctions-ui pull request #468
Opened 2022-09-21 12:55 UTC by aomafarag

Closes #450.

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

Issues to be fixed:
- [x] Fix uniswap price fetching when there is no bids
- [x] Set `nextMinimumBid` to make sense (eg a uniswap price * gap to reach 1k net profit)
- [x] `SurplusAuctionBidTransactionTable` "state" should display state, not just date
- [x] `SurplusAuctionBidTransactionTable` end state should count down, but count up (ie Ended 2s ago, 3s ago, etc. First guess: can be caused by invalid determination of the `earliestEndDate`)

2022-09-21 14:38 UTC, valiafetisov commented
> Set `nextMinimumBid` to make sense (eg a uniswap price * gap to reach 1k net profit)

Why was it not addressed in this PR? I understand that it's not the UI problem, but you basically need to fix `nextMinimumBid` in the core to set a valid default instead of 0

2022-09-21 15:12 UTC, valiafetisov commented
Initially, there is no `bidAmountMKR` as there is no bids yet. But you only need to check if `nextMinimumBid` is zero to set it to another default, since 0 is not a valid bid amount

2022-09-21 17:19 UTC, valiafetisov approved these changes

2022-09-22 07:37 UTC, LukSteib requested changes
- [ ] For me uniswap price still not fetched properly (see 1 below)


1
<img width="600" alt="image" src="https://user-images.githubusercontent.com/36229155/191686378-d69bd80d-736f-449c-be9e-83471e0f3a93.png">

2022-09-22 11:07 UTC, valiafetisov commented
Not sure I fully understand without a link to the source code where the problem is. What is the proposed solution?

2022-09-22 11:24 UTC, valiafetisov commented
> the auctions are not enriched in that first case

Ok, the problem is reproduced. Do you want to investigate why is it not enriched in this case and propose a solution?

2022-09-22 14:11 UTC, valiafetisov commented
Since we want to show "unit price" and not the total price for the whole collateral, we can (only in case when there is no bids yet) compute `marketUnitPrice` using arbitrary number, eg `1`. The price will be different in case the bid amount will be significantly bigger, but I think it's better to show at least some kind of unit price as a reference than no unit price at all. Since then the user will still need to go to external platform to get it. Do you agree, @LukSteib?

2022-09-22 15:54 UTC, LukSteib commented
> Do you agree, @LukSteib

Agree to the propsal by @valiafetisov. Better to use arbitrary number (in this case `1`) than none.

2022-09-22 16:37 UTC, valiafetisov approved these changes

2022-09-22 17:22 UTC, LukSteib approved these changes

2022-09-22 18:32 UTC, merged