Create `WithdrawDaiFromVat` component and stories
sidestream-tech/unified-auctions-ui pull request #482
Opened 2022-09-27 14:57 UTC by aomafarag

Closes #473.

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

### Assets

1. Panel
![Screenshot from 2022-09-27 16-54-33](https://user-images.githubusercontent.com/85403429/192561083-50611f07-6fc8-4aa3-9b4b-1e24e0a12417.png)

2. Vault transaction
![Screenshot from 2022-09-27 16-55-51](https://user-images.githubusercontent.com/85403429/192561431-61965ba3-a9ae-446a-be77-9ac772f2a11d.png)

3. Vault page
![Screenshot from 2022-09-27 16-57-11](https://user-images.githubusercontent.com/85403429/192561747-3ea561c0-c2f6-477b-82bf-cf79aa730119.png)

2022-09-28 13:25 UTC, LukSteib requested changes
- [x] Can we concatenate the tx hash of the table on the transaction page. Although horizontal scroll of the side panel works, it still looks broken and I expect that we can show all three columns if we reduce size of the tx hash column (see s1 below)
- [x] We do not properly fetch DAI in VAT after liquidation. The introduced withdrawal panel is not refreshed with the correct DAI balance until opening the wallet management popup (see s2)
- [ ] Once the DAI in VAT amount is fetched correctly the auth state is no longer displayed correctly (see r1 below). One has to click the auth button again and without an actual tx it's in the correct state then.



S1
<img width="694" alt="Screenshot 2022-09-28 at 15 16 19" src="https://user-images.githubusercontent.com/36229155/192789064-97fbd8a8-f751-42a1-a1fb-5e4ff17f222f.png">



S2:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/36229155/192788973-80140f79-2b07-4456-8b40-ecc8a5de0115.png">

r1
https://www.loom.com/share/5d74709337c9461c919590879f4566c8

2022-09-28 13:43 UTC, zoey-kaiser requested changes

2022-09-28 13:43 UTC, zoey-kaiser commented on frontend/components/vault/Vault.vue
> +                <table class="table-auto mt-4">
How will this table look in dark mode? Have a look at #311 where I added a similar table and added styling for light and dark mode!

2022-09-28 13:43 UTC, zoey-kaiser commented on frontend/components/vault/Vault.vue
> +                            <td><FormatAddress :value="liquidation.transactionHash" /></td>
Agree with Lukas here to minimize the transactionhash!

2022-09-28 13:43 UTC, zoey-kaiser commented on frontend/components/vault/WithdrawDaiFromVat.vue
> +            <WalletAuthorizationCheckPanel
Do we want to add a `WalletConnectionCheck` panel here too? Incase someone views it without having their wallet connected? (Super edge case, I know!)

2022-09-28 13:43 UTC, zoey-kaiser commented on frontend/components/vault/WithdrawDaiFromVat.vue
> +                Withdraw DAI partially
I would rephrase this to:

"Partially withdraw DAI", I think that sounds better.

Or do we take another description, as this opens the VAT modal right? Something in the direction of:

"Manage VAT"?

2022-09-28 13:43 UTC, zoey-kaiser commented on frontend/components/vault/WithdrawDaiFromVat.vue
> +        daiVatBalance: {
This is something Valia and I discussed a while ago. This component does not work without `daiVatBalance` and a few other props. Therefore we should stop making these props optional and just add a `v-if` on the component in the parent to ensure it is hidden when in this case no wallet is connected. 

This is better for testing, as if it is ever not properly hidden or a value is not correctly passed, we get a error thrown during the tests. 

(If the prop is only optional we may never know we forgot to pass it somewhere)

2022-09-28 13:43 UTC, zoey-kaiser commented on frontend/components/vault/WithdrawDaiFromVat.vue
> +            default: 'liquidatable',
This should also never be set as default! Lets make it required.

2022-09-28 13:43 UTC, zoey-kaiser commented on frontend/components/vault/WithdrawDaiFromVat.vue
> +        currentStateAndTitle(): PanelProps {
You also have no state here what to display if no wallet is connected! 

This related to my other two points: Will we ever show this panel in a state if no wallet is connected?

YES: Keep the props optional and add a state here to handle it
NO: Make the props above required, to ensure there wont be an issue here!

2022-09-28 13:43 UTC, zoey-kaiser commented on frontend/containers/VaultsContainer.vue
> +        daiVatBalance(): BigNumber | undefined {
Why do we have this extra? Can't you just pass `walletbalances?.walletVATDAI` directly in the component above?

2022-09-29 11:02 UTC, zoey-kaiser requested changes

2022-09-29 11:02 UTC, zoey-kaiser commented on frontend/components/vault/WithdrawDaiFromVat.vue
> +            default: undefined,
These are all still set with a default value. My recommendation was to set these to required.

```suggestion
            required: true,
```

2022-09-29 11:02 UTC, zoey-kaiser commented on frontend/components/vault/WithdrawDaiFromVat.vue
> +            default: undefined,
Same here

2022-09-29 14:14 UTC, zoey-kaiser approved these changes

2022-09-29 14:58 UTC, LukSteib requested changes
- [x] the two problems raised in prev review comment haven't been addressed (any update on those? 
- [ ] additionally: IMO there is no need for the blue info message on top of the transaction page (see screenshot below). The table covers this information already. So I would suggest to only keep this on the liquidation page 

<img width="677" alt="image" src="https://user-images.githubusercontent.com/36229155/193066636-2265d404-bfc7-4335-a096-304f44b11c7b.png">

2022-10-04 07:28 UTC, LukSteib commented
> That way, the user can easily navigate to that latest transaction if they were the one who had just executed it.

Fine for me to display it.

2022-10-04 08:56 UTC, valiafetisov commented on frontend/components/vault/VaultLiquidationTransactionFlow.vue
> +                <WithdrawDaiFromVat
Does this panel have rounded corners at the moment? Otherwise, let's put it into a separate empty div, so it will have them

2022-10-04 08:56 UTC, valiafetisov commented on frontend/components/vault/WithdrawDaiFromVat.vue
> +        <template #title>{{ currentStateAndTitle.title }}</template>
Why was this component copied over? I can see the identical `WithdrawDAIPanel` that should've been reused instead

2022-10-05 14:07 UTC, LukSteib approved these changes

2022-10-06 09:54 UTC, merged