Display liquidatable amount
sidestream-tech/unified-auctions-ui pull request #488
Opened 2022-10-06 14:54 UTC by aomafarag

Closes #486.

![Screenshot from 2022-10-06 17-28-20](https://user-images.githubusercontent.com/85403429/194355130-2c586dfd-7480-4fb9-91be-ce4c5b4fdbbe.png)

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

2022-10-06 15:38 UTC, zoey-kaiser requested changes

2022-10-06 15:38 UTC, zoey-kaiser commented on frontend/components/panels/WithdrawDAIPanel.vue
> -                :disabled="!isWalletConnected || !isWalletAuthorized || !hasDaiToWithdraw || isRefreshing"
Why did we remove the isRefreshing? If we are retrieving new values from the chain we don't want the user to execute any transactions as the data may be outdated. 

We also don't want the button to be loading while refreshing, as we use the loading indicator to show if the user is withdrawing.

2022-10-12 13:46 UTC, zoey-kaiser submitted a review, later dismissed

2022-10-13 15:41 UTC, valiafetisov commented
Replication URL https://unified-auctions.makerdao.com/vaults?network=mainnet&vault=20775

2022-10-14 07:38 UTC, LukSteib commented
> Else, render Should be liquidated instead, with the vault debt as its value, and add an Explain text explaining that vaults cannot be partially or fully liquidated unless they are in a liquidatable state.

To me this sounds like confusing UX. The `VaultLiquidationLimitsCheckPanel` should only check if limits are reached or not without incorporating the vaults' liquidation state into the logic. So in the example case above I would expect that
* `VaultLiquidationLimitsCheckPanel` is shown in "Partial liquidation possible" state
* "Maximum liquidation amount" and "Will be liquidated" figures are displayed (in current state I would expect 5.000.000 to be displayed here)

2022-10-14 11:59 UTC, KirillDogadin-std commented
To me it seems like all the numbers you need are already exposed to the frontend.

Rephrasing your goal: you want to show if liquidation is possible / partially possible / impossible based on the limits only and neglect all the other factors that play into the determining the liquidatability state.

Hence:
  - you know the leftovers in the limits already,
  - you know the amount of debt in the vault
  - you know the minimal allowed leftower of the vault. (`minimalAuctionedDai`)

This means you're able to implement the following:

  - if the debt is less than the available limit - black coloring
  - if the debt is greater than the available limit - this is potentially partial liquidation.
    - if the leftover after partial liquidation is less than `minimalAuctionedDai` OR the auctioned amount is less than `minimalAuctionedDai` - red coloring
    - else orange coloring
  - if the limits are reached - red coloring

No such tool in the core. You can the function that returns 1 of 3 states based on the logic above and call it in the store.

2022-10-19 11:16 UTC, valiafetisov commented
The new mock

![MakerDAO vaults@2x](https://user-images.githubusercontent.com/3393626/196676423-06796a01-c96c-4e0f-84d6-e8bf6dcbdafc.png)

2022-10-21 07:13 UTC, LukSteib requested changes
Taking the same vault as reference (see below) - vaultID: 20775 (mainnet)

- [ ] I don't like the color coding - to me neither red nor orange color coding adds any value. I would propose to not use the number color coding

Other than that it's fine for me


<img width="666" alt="image" src="https://user-images.githubusercontent.com/36229155/197134832-571d449d-a891-40ec-9ec8-1007af8bf5b6.png">

2022-10-26 13:53 UTC, LukSteib approved these changes

2022-11-03 14:11 UTC, merged