Reintegrate refresh logic
sidestream-tech/unified-auctions-ui pull request #490
Opened 2022-10-07 10:52 UTC by aomafarag

Closes #489.

![Screenshot from 2022-10-07 12-38-14](https://user-images.githubusercontent.com/85403429/194537144-8cbc66b1-5683-4aa2-9dac-ae8cf5563df1.png)

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

2022-10-07 11:00 UTC, zoey-kaiser requested changes

2022-10-07 11:00 UTC, zoey-kaiser commented on frontend/components/panels/WithdrawDAIPanel.vue
> +        isRefreshing: {
Do we want to rename this to just `disabled`? We currently only provide named actions when it actually changes something specific to this panel (Like a loading icon, texts etc). 

Changing it to disabled just makes it extendable if we ever need to disable it for another reason.

2022-10-07 11:00 UTC, zoey-kaiser commented on frontend/components/auction/surplus/SurplusAuctionTransactionFlow.stories.js
> +        isWalletAuthorized: false,
Why do we add this here? Was it forgotten?

2022-10-12 10:25 UTC, zoey-kaiser approved these changes

2022-10-12 13:38 UTC, valiafetisov approved these changes

2022-10-12 13:38 UTC, merged