Add electron-builder workflow
sidestream-tech/unified-auctions-ui pull request #590
Opened 2023-02-13 13:18 UTC by aomafarag

Closes #585.

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

2023-02-16 14:44 UTC, valiafetisov commented on .github/workflows/build-electron-app.yaml
> +          github_token: ${{ secrets.github_token }}
But my question was `why`? Can you provide link to the documentation that explains why it's needed, any other source or at least exact error which is thrown?

2023-02-16 14:50 UTC, valiafetisov commented on .github/workflows/build-electron-app.yaml
> +        os: [macos-latest, ubuntu-latest, windows-latest]
Does this job needs to run on all three platforms? I thought it only publishes the files, build is already done

2023-02-16 14:50 UTC, valiafetisov commented on .github/workflows/build-electron-app.yaml
> +          github_token: ${{ secrets.github_token }}
If this action gets `github_token` it's the same as giving write permissions (but maybe even more than that). Then, I don't actually see the need to split this process into 3 jobs and see the need to pin version of this action (via the hash) as well

2023-02-21 08:31 UTC, valiafetisov submitted a review, later dismissed

2023-02-21 08:41 UTC, LukSteib commented
Can you give me a quick explainer how I am supposed to test this?

2023-02-21 11:09 UTC, valiafetisov commented
> Can you give me a quick explainer how I am supposed to test this?

I've thought that you have already tested previously. I think it should be possible by
1. Forking this repo into your private github account
2. Merging this PR into main
3. Making an empty release
4. Waiting for the CI to finish and add files to the release by editing it

[(not sure if you need to have paid account for this to work)](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes)

2023-02-23 08:24 UTC, LukSteib requested changes
For review I did the following steps: 
* forked this repo
* triggered a release from the `electron-builder-workflow` branch

- [ ] The Git CI ran into problems. Posting screenshots and errors below

<img width="425" alt="image" src="https://user-images.githubusercontent.com/36229155/220855215-a9bafaf2-f468-405b-ac2d-692605fe1b50.png">
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/36229155/220855354-68d2ba15-725b-40a1-8e92-e438a4b94018.png">

2023-03-02 08:34 UTC, LukSteib commented
> Please copy the [file from my fork](https://github.com/aomafarag/unified-auctions-ui/blob/main/electron/package.json), making sure to change repository.url to your fork's URL.

This means I'd have to open a PR for my fork and update the `package.json` accordingly, right?

2023-03-02 11:41 UTC, LukSteib approved these changes
Approving this. Was able to test release on fork

<img width="479" alt="image" src="https://user-images.githubusercontent.com/36229155/222418664-b0f87a06-47e8-4b47-a689-4fb79c7e857f.png">

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/36229155/222418761-6c993523-05f3-4501-ab6f-df05cb90bfee.png">

2023-03-06 09:05 UTC, valiafetisov approved these changes

2023-03-06 09:07 UTC, merged