UI adjustments for sky
sidestream-tech/unified-auctions-ui pull request #619
Opened 2024-09-03 09:54 UTC by DaeunYoon

Closes #

Checklist:
- [ ] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [ ] issue checkboxes are all addressed
- [ ] manually checked my feature / not applicable
- [ ] wrote tests / not applicable
- [ ] attached screenshots / not applicable

2024-09-03 14:57 UTC, LukSteib requested changes
- [x] NIT: On hover of this primary button the button caption becomes barely readable (see s1). Can we change that in a way that it's still readable (e.g. white)

s1
<img width="150" alt="Screenshot 2024-09-03 at 16 56 06" src="https://github.com/user-attachments/assets/543567ee-ae5b-4c23-b55f-cc921135fbe2">

2024-09-04 12:59 UTC, DaeunYoon commented
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/f4dd9a41-e05b-4ea4-af10-3d42d25f1028">
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/40b6d550-3733-499f-829f-078d9f61080e">

fyi: we need to update `preview` image that is used for twitter card later on as well :)

2024-09-04 13:43 UTC, LukSteib submitted a review, later dismissed

2024-09-04 13:47 UTC, DaeunYoon commented on frontend/assets/styles/ant-design-dark.less
> +    @import '~ant-design-vue/lib/style/components';
I'm not sure this file linting was proper before (it had tab-width 2 before and have 4 now)

2024-09-04 15:02 UTC, valiafetisov commented on frontend/components/layout/Header.vue
> +                bg-gradient-to-r
Nit: let's maybe try using either just semi-transparent white/gray color here or top-to-bottom gradient. I don't see in the Brand Guideline any gradient that is left to right.

2024-09-04 15:14 UTC, DaeunYoon commented on frontend/components/auction/TransactionMessage.vue
> +            default: false,
I thought this default value isn't truethful anymore :/ 
I reverted this commit now!

2024-09-04 16:19 UTC, DaeunYoon commented on frontend/layouts/default.vue
> -            :production-banner-url="productionBannerURL"
I added the variable back, but not sure `StagingBanner` uses `productionBannerURL`.
I removed it with `banner that refers to the electron app` which was outlined in the issue. Do you think we need to bring this one back as well?

2024-09-04 16:51 UTC, DaeunYoon commented
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/4d0bc0c8-9351-49ef-b7ae-d54be2fd56fc">
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/b8076fa2-2692-4721-908f-258c69e99e3b">

2024-09-04 19:24 UTC, valiafetisov commented
Did some minor tweaks to the colors based on the Brand Guideline.

<details><summary>Screenshots</summary>

<img width="1552" alt="Screenshot 2024-09-04 at 21 18 16" src="https://github.com/user-attachments/assets/c911ce53-cf5d-4079-9e1e-22126e914e01">
<img width="1552" alt="Screenshot 2024-09-04 at 21 18 23" src="https://github.com/user-attachments/assets/ec4b61d7-4d97-48f3-aa7a-2fe75399c90b">
<img width="386" alt="Screenshot 2024-09-04 at 21 21 16" src="https://github.com/user-attachments/assets/ccdb5b75-87ac-4ab3-a95a-a223e70617a1">

</details>

2024-09-04 19:31 UTC, valiafetisov submitted a review, later dismissed

2024-09-04 19:53 UTC, LukSteib reviewed
Sorry for NIT picking:

- [ ] ensure that font in dropdown for network and wallet has other color than black (e.g. white) because currently hard to read

s1
<img width="226" alt="image" src="https://github.com/user-attachments/assets/635fc948-72b8-4d64-b739-af94ae998062">

2024-09-05 07:55 UTC, DaeunYoon commented
<img width="831" alt="image" src="https://github.com/user-attachments/assets/0136a7d3-a529-4972-a1ee-1f8b89803ad7">

2024-09-05 08:01 UTC, valiafetisov approved these changes

2024-09-05 08:08 UTC, valiafetisov commented on frontend/layouts/default.vue
> -            :production-banner-url="productionBannerURL"
Ah, maybe it's just a confusing name of the variable. This can be tested by providing `PRODUCTION_BANNER_URL` env variable to the frontend

2024-09-05 08:19 UTC, merged